/**
 * DATA PRIVACY & AI DISCLOSURE SCREEN
 * 
 * Apple App Store 2024 REQUIREMENT:
 * Apps using AI/ML features must disclose:
 * - What AI features are used
 * - What data is sent to AI services
 * - How AI-generated content is labeled
 */

import { StyleSheet, Text, View, ScrollView, TouchableOpacity } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { colors, spacing, typography, radii } from '@/theme/tokens';

import { MainStackParamList } from '@/navigation/RootNavigator';
import { BackButton } from '@/components/BackButton';

type Props = NativeStackScreenProps<MainStackParamList, 'DataPrivacy'>;

export const DataPrivacyScreen = ({ navigation }: Props) => {
  return (
    <SafeAreaView style={styles.container}>
      <BackButton onPress={() => navigation.goBack()} />

      <ScrollView 
        style={styles.scrollView}
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}
      >
        <Text style={styles.title}>AI & Data Usage</Text>
        <Text style={styles.subtitle}>
          We believe in transparency. Here is exactly how AI powers your readings.
        </Text>

        <View style={styles.heroCard}>
          <Text style={styles.heroIcon}>◎</Text>
          <Text style={styles.heroTitle}>AI-Powered Readings</Text>
          <Text style={styles.heroText}>
            Your personalized astrological readings are generated by advanced AI language models, interpreting astronomical calculations from Swiss Ephemeris.
          </Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>How Your Readings Are Created</Text>
          
          <View style={styles.flowStep}>
            <View style={styles.flowNumber}><Text style={styles.flowNumberText}>1</Text></View>
            <View style={styles.flowContent}>
              <Text style={styles.flowTitle}>You Enter Birth Data</Text>
              <Text style={styles.flowDesc}>Date, time, and location of birth</Text>
            </View>
          </View>

          <View style={styles.flowLine} />

          <View style={styles.flowStep}>
            <View style={styles.flowNumber}><Text style={styles.flowNumberText}>2</Text></View>
            <View style={styles.flowContent}>
              <Text style={styles.flowTitle}>Swiss Ephemeris Calculates</Text>
              <Text style={styles.flowDesc}>Precise planetary positions are computed</Text>
            </View>
          </View>

          <View style={styles.flowLine} />

          <View style={styles.flowStep}>
            <View style={styles.flowNumber}><Text style={styles.flowNumberText}>3</Text></View>
            <View style={styles.flowContent}>
              <Text style={styles.flowTitle}>AI Interprets</Text>
              <Text style={styles.flowDesc}>Language models generate personalized interpretations</Text>
            </View>
          </View>

          <View style={styles.flowLine} />

          <View style={styles.flowStep}>
            <View style={styles.flowNumber}><Text style={styles.flowNumberText}>4</Text></View>
            <View style={styles.flowContent}>
              <Text style={styles.flowTitle}>Audio is Narrated</Text>
              <Text style={styles.flowDesc}>AI text-to-speech creates your audio reading</Text>
            </View>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>AI Services We Use</Text>
          
          <View style={styles.serviceCard}>
            <Text style={styles.serviceIcon}>◇</Text>
            <View style={styles.serviceContent}>
              <Text style={styles.serviceName}>DeepSeek</Text>
              <Text style={styles.serviceUse}>Primary text generation</Text>
            </View>
          </View>

          <View style={styles.serviceCard}>
            <Text style={styles.serviceIcon}>◈</Text>
            <View style={styles.serviceContent}>
              <Text style={styles.serviceName}>Anthropic Claude</Text>
              <Text style={styles.serviceUse}>Extended analysis</Text>
            </View>
          </View>

          <View style={styles.serviceCard}>
            <Text style={styles.serviceIcon}>◆</Text>
            <View style={styles.serviceContent}>
              <Text style={styles.serviceName}>OpenAI GPT</Text>
              <Text style={styles.serviceUse}>Backup generation</Text>
            </View>
          </View>

          <View style={styles.serviceCard}>
            <Text style={styles.serviceIcon}>♪</Text>
            <View style={styles.serviceContent}>
              <Text style={styles.serviceName}>Chatterbox TTS (RunPod)</Text>
              <Text style={styles.serviceUse}>Audio narration</Text>
            </View>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Data We Send to AI</Text>
          
          <View style={styles.dataCard}>
            <View style={styles.dataRow}>
              <Text style={styles.dataCheck}>✓</Text>
              <Text style={styles.dataText}>Birth date, time, location</Text>
            </View>
            <View style={styles.dataRow}>
              <Text style={styles.dataCheck}>✓</Text>
              <Text style={styles.dataText}>Calculated planetary positions</Text>
            </View>
            <View style={styles.dataRow}>
              <Text style={styles.dataCheck}>✓</Text>
              <Text style={styles.dataText}>Relationship preferences</Text>
            </View>
          </View>

          <View style={styles.dataCardNo}>
            <Text style={styles.dataCardTitle}>We NEVER Send:</Text>
            <View style={styles.dataRow}>
              <Text style={styles.dataX}>✗</Text>
              <Text style={styles.dataTextNo}>Your name or email</Text>
            </View>
            <View style={styles.dataRow}>
              <Text style={styles.dataX}>✗</Text>
              <Text style={styles.dataTextNo}>Payment information</Text>
            </View>
            <View style={styles.dataRow}>
              <Text style={styles.dataX}>✗</Text>
              <Text style={styles.dataTextNo}>Device identifiers</Text>
            </View>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Important Disclosures</Text>
          
          <View style={styles.disclosureCard}>
            <Text style={styles.disclosureTitle}>○ AI-Generated Content</Text>
            <Text style={styles.disclosureText}>
              All readings are AI-generated. This is entertainment, not professional advice.
            </Text>
          </View>

          <View style={styles.disclosureCard}>
            <Text style={styles.disclosureTitle}>▣ Secure Transmission</Text>
            <Text style={styles.disclosureText}>
              Data is encrypted. AI providers dont store your data.
            </Text>
          </View>

          <View style={styles.disclosureCard}>
            <Text style={styles.disclosureTitle}>× No Training</Text>
            <Text style={styles.disclosureText}>
              We request providers not use your data for AI training.
            </Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Your Control</Text>
          <Text style={styles.controlText}>
            Delete all your data anytime via Settings - Delete Account.
          </Text>
          <TouchableOpacity 
            style={styles.deleteButton}
            onPress={() => navigation.navigate('AccountDeletion')}
          >
            <Text style={styles.deleteButtonText}>Manage Account Deletion</Text>
          </TouchableOpacity>
        </View>

        <View style={styles.footer}>
          <Text style={styles.footerTitle}>Questions?</Text>
          <Text style={styles.footerEmail}>privacy@oneinabillion.app</Text>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  header: { paddingHorizontal: spacing.page, paddingVertical: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.divider },
  backButton: { paddingVertical: spacing.xs },
  backText: { fontFamily: typography.sansMedium, fontSize: 16, color: colors.primary },
  scrollView: { flex: 1 },
  scrollContent: { paddingHorizontal: spacing.page, paddingVertical: spacing.xl },
  title: { fontFamily: typography.headline, fontSize: 32, color: colors.text, marginBottom: spacing.sm },
  subtitle: { fontFamily: typography.sansRegular, fontSize: 16, color: colors.mutedText, lineHeight: 24, marginBottom: spacing.xl },
  heroCard: { backgroundColor: colors.primarySoft, padding: spacing.xl, borderRadius: radii.card, alignItems: 'center', marginBottom: spacing.xl, borderWidth: 1, borderColor: colors.primary + '30' },
  heroIcon: { fontSize: 48, marginBottom: spacing.md },
  heroTitle: { fontFamily: typography.serifBold, fontSize: 22, color: colors.text, textAlign: 'center', marginBottom: spacing.sm },
  heroText: { fontFamily: typography.sansRegular, fontSize: 15, color: colors.text, textAlign: 'center', lineHeight: 22 },
  section: { marginBottom: spacing.xl },
  sectionTitle: { fontFamily: typography.serifBold, fontSize: 20, color: colors.text, marginBottom: spacing.md },
  flowStep: { flexDirection: 'row', alignItems: 'flex-start' },
  flowNumber: { width: 32, height: 32, borderRadius: 16, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center', marginRight: spacing.md },
  flowNumberText: { fontFamily: typography.sansSemiBold, fontSize: 16, color: '#fff' },
  flowContent: { flex: 1, paddingTop: 4 },
  flowTitle: { fontFamily: typography.sansSemiBold, fontSize: 16, color: colors.text },
  flowDesc: { fontFamily: typography.sansRegular, fontSize: 14, color: colors.mutedText, marginTop: 4 },
  flowLine: { width: 2, height: 20, backgroundColor: colors.divider, marginLeft: 15, marginVertical: spacing.xs },
  serviceCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.surface, padding: spacing.md, borderRadius: radii.card, marginBottom: spacing.sm, borderWidth: 1, borderColor: colors.border },
  serviceIcon: { fontSize: 28, width: 48 },
  serviceContent: { flex: 1 },
  serviceName: { fontFamily: typography.sansSemiBold, fontSize: 16, color: colors.text },
  serviceUse: { fontFamily: typography.sansRegular, fontSize: 14, color: colors.mutedText, marginTop: 2 },
  dataCard: { backgroundColor: colors.surface, padding: spacing.lg, borderRadius: radii.card, marginBottom: spacing.md, borderWidth: 1, borderColor: colors.border },
  dataCardNo: { backgroundColor: '#FFF5F5', padding: spacing.lg, borderRadius: radii.card, marginBottom: spacing.md, borderWidth: 1, borderColor: colors.primary + '30' },
  dataCardTitle: { fontFamily: typography.sansSemiBold, fontSize: 14, color: colors.primary, marginBottom: spacing.sm },
  dataRow: { flexDirection: 'row', alignItems: 'center', marginBottom: spacing.xs },
  dataCheck: { fontFamily: typography.sansBold, fontSize: 16, color: colors.success, width: 28 },
  dataX: { fontFamily: typography.sansBold, fontSize: 16, color: colors.primary, width: 28 },
  dataText: { fontFamily: typography.sansRegular, fontSize: 15, color: colors.text },
  dataTextNo: { fontFamily: typography.sansRegular, fontSize: 15, color: colors.text },
  disclosureCard: { backgroundColor: colors.surface, padding: spacing.lg, borderRadius: radii.card, marginBottom: spacing.md, borderWidth: 1, borderColor: colors.border },
  disclosureTitle: { fontFamily: typography.sansSemiBold, fontSize: 16, color: colors.text, marginBottom: spacing.sm },
  disclosureText: { fontFamily: typography.sansRegular, fontSize: 14, color: colors.mutedText, lineHeight: 22 },
  controlText: { fontFamily: typography.sansRegular, fontSize: 15, color: colors.text, lineHeight: 24, marginBottom: spacing.md },
  deleteButton: { borderWidth: 1, borderColor: colors.primary, paddingVertical: spacing.md, borderRadius: radii.button, alignItems: 'center' },
  deleteButtonText: { fontFamily: typography.sansSemiBold, fontSize: 15, color: colors.primary },
  footer: { alignItems: 'center', paddingTop: spacing.xl, borderTopWidth: 1, borderTopColor: colors.divider },
  footerTitle: { fontFamily: typography.serifBold, fontSize: 18, color: colors.text, marginBottom: spacing.sm },
  footerEmail: { fontFamily: typography.sansSemiBold, fontSize: 16, color: colors.primary },
});




