/**
 * TERMS OF SERVICE SCREEN
 * 
 * Apple App Store REQUIRED - must be accessible from within the app.
 * User agreement, subscription terms, and refund policy.
 */

import { StyleSheet, Text, View, ScrollView, TouchableOpacity } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { colors, spacing, typography } from '@/theme/tokens';
import { MainStackParamList } from '@/navigation/RootNavigator';
import { BackButton } from '@/components/BackButton';

type Props = NativeStackScreenProps<MainStackParamList, 'TermsOfService'>;

const LAST_UPDATED = 'January 11, 2026';

const SECTIONS = [
  {
    content: `By downloading, installing, or using the 1 in a Billion application ("App"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not use the App.

These Terms constitute a legally binding agreement between you and **SwiftBuy Solutions LLC** ("Company," "we," "us," or "our"), based in Dubai, U.A.E.`,
  },
  {
    title: 'Description of Service',
    content: `1 In A Billion provides personalized astrological readings and compatibility analyses using:

• Swiss Ephemeris for precise astronomical calculations
• Multiple astrological systems (Western, Vedic, Human Design, Gene Keys, Kabbalah)
• AI-powered text generation for interpretations
• Audio narration of readings

The App is intended for entertainment and self-reflection purposes. Astrological readings should not be used as the sole basis for important life decisions.`,
  },
  {
    title: 'User Eligibility',
    content: `To use the App, you must:

• Be at least 18 years of age
• Have the legal capacity to enter into binding agreements
• Not be prohibited from using the App under applicable laws

By using the App, you represent and warrant that you meet these eligibility requirements.`,
  },
  {
    title: 'Account Registration',
    content: `You may be required to create an account to access certain features. You agree to:

• Provide accurate, current, and complete information
• Maintain the security of your account credentials
• Notify us immediately of any unauthorized access
• Accept responsibility for all activities under your account

We reserve the right to suspend or terminate accounts that violate these Terms.`,
  },
  {
    content: `**Payments**:
• All purchases for horoscope readings and premium features are processed through **Stripe**
• Prices are displayed in your local currency
• Due to the personalized nature of our digital content, **all purchases are final and non-refundable**

**Available Products**:
• Individual readings: $14 per system (5 pages, 13 min audio)
• Complete Reading (all 5 systems): $34 (25 pages, 1h 5m audio) - 50% off
• Compatibility overlay: $41 per system (15 pages, 39 min audio)
• Nuclear Package: $108 (100 pages, 3h 28m audio) - 50% off

**Refund Policy**:
• We do not offer refunds once a reading has been purchased and processed
• In the event of a technical failure (e.g., reading not delivered), we provide a **Manual Fix**
• To request a manual fix, please contact our support team at **contact@1-in-a-billion.app**

**Restore Purchases**:
• You can restore previous purchases identified by your email or device through the Settings menu`,
  },
  {
    title: 'Intellectual Property',
    content: `**Our Content**:
All content in the App, including text, graphics, logos, images, audio, and software, is owned by or licensed to us and protected by intellectual property laws.

**Generated Readings**:
Readings generated for you are licensed for your personal, non-commercial use. You may:
• Save and share your readings
• Print copies for personal use

You may NOT:
• Resell or commercially distribute readings
• Claim AI-generated content as your own original work
• Remove copyright notices or attributions`,
  },
  {
    title: 'User Conduct',
    content: `You agree NOT to:

• Use the App for any illegal purpose
• Attempt to reverse engineer or hack the App
• Interfere with other users' enjoyment of the App
• Submit false or misleading information
• Use automated systems to access the App
• Violate any applicable laws or regulations
• Harass, abuse, or harm others through the App`,
  },
  {
    title: 'AI-Generated Content Disclaimer',
    content: `**Important Notice**:

The readings and interpretations provided by this App are generated by artificial intelligence systems. While we strive for accuracy and meaningful insights:

• AI interpretations are not a substitute for professional advice
• Astrological readings are for entertainment and self-reflection
• Results may vary and are not guaranteed
• The App does not provide medical, legal, financial, or psychological advice

Always consult qualified professionals for important life decisions.`,
  },
  {
    title: 'Limitation of Liability',
    content: `TO THE MAXIMUM EXTENT PERMITTED BY LAW:

• The App is provided "as is" without warranties of any kind
• We do not guarantee uninterrupted or error-free service
• We are not liable for any indirect, incidental, or consequential damages
• Our total liability shall not exceed the amount you paid us in the past 12 months

Some jurisdictions do not allow certain limitations, so some of these may not apply to you.`,
  },
  {
    title: 'Indemnification',
    content: `You agree to indemnify and hold harmless One In A Billion Ltd., its officers, directors, employees, and agents from any claims, damages, losses, or expenses arising from:

• Your use of the App
• Your violation of these Terms
• Your violation of any third-party rights`,
  },
  {
    title: 'Termination',
    content: `We may suspend or terminate your access to the App at any time for:

• Violation of these Terms
• Suspected fraudulent or illegal activity
• Extended periods of inactivity
• Any other reason at our sole discretion

Upon termination, your right to use the App ceases immediately. Provisions that by their nature should survive termination will remain in effect.`,
  },
  {
    title: 'Changes to Terms',
    content: `We reserve the right to modify these Terms at any time. We will notify you of material changes by:

• Posting updated Terms in the App
• Sending a notification through the App
• Updating the "Last Updated" date

Continued use of the App after changes constitutes acceptance of the new Terms.`,
  },
  {
    title: 'Governing Law',
    content: `These Terms shall be governed by and construed in accordance with the laws of the **United Arab Emirates**.

Any disputes arising from these Terms or the App shall be resolved in the courts of **Dubai, U.A.E.**`,
  },
  {
    title: 'Contact Information',
    content: `For questions about these Terms, or for technical support:

Email: **contact@1-in-a-billion.app**
Address:
SwiftBuy Solutions LLC
Meydan Grandstand, 6th floor
Meydan Road, Nad Al Sheba
Dubai, U.A.E.`,
  },
];

export const TermsOfServiceScreen = ({ navigation }: Props) => {
  return (
    <SafeAreaView style={styles.container}>
      <BackButton onPress={() => navigation.goBack()} />

      <ScrollView 
        style={styles.scrollView}
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}
      >
        {/* Title */}
        <Text style={styles.title}>Terms of Service</Text>
        <Text style={styles.lastUpdated}>Last updated: {LAST_UPDATED}</Text>

        {/* Sections */}
        {SECTIONS.map((section, index) => (
          <View key={index} style={styles.section}>
            <Text style={styles.sectionTitle}>{section.title}</Text>
            <Text style={styles.sectionContent}>{section.content}</Text>
          </View>
        ))}

        {/* Footer */}
        <View style={styles.footer}>
          <Text style={styles.footerText}>
            By using 1 In A Billion, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service.
          </Text>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: spacing.page,
    paddingVertical: spacing.xl,
  },
  title: {
    fontFamily: typography.headline,
    fontSize: 32,
    color: colors.text,
    marginBottom: spacing.sm,
  },
  lastUpdated: {
    fontFamily: typography.sansRegular,
    fontSize: 14,
    color: colors.mutedText,
    marginBottom: spacing.xl,
  },
  section: {
    marginBottom: spacing.xl,
  },
  sectionTitle: {
    fontFamily: typography.serifBold,
    fontSize: 20,
    color: colors.text,
    marginBottom: spacing.sm,
  },
  sectionContent: {
    fontFamily: typography.sansRegular,
    fontSize: 15,
    color: colors.text,
    lineHeight: 24,
  },
  footer: {
    marginTop: spacing.lg,
    paddingTop: spacing.lg,
    borderTopWidth: 1,
    borderTopColor: colors.divider,
  },
  footerText: {
    fontFamily: typography.sansRegular,
    fontSize: 14,
    color: colors.mutedText,
    textAlign: 'center',
    fontStyle: 'italic',
  },
});




